#ifndef _REGISTRATION_STATE
#define _REGISTRATION_STATE

enum class REGISTRATION_STATE
{
	CURRENTLY_DEREGISTERED,
	PENDING_REGISTRATION,
	CURRENTLY_REGISTERED,
	PENDING_DEREGISTRATION
};

#endif _REGISTRATION_STATE
